function Export-TapGenerationReport {
    param(
        [Parameter(Mandatory)]
        $Results,
        
        [Parameter(Mandatory)]
        [string]$OutputDir,
        
        [Parameter()]
        [string]$ReportName = "TAP_Report"
    )
    
    $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $htmlPath = Join-Path $OutputDir "$($ReportName)_$timestamp.html"
    $csvPath = Join-Path $OutputDir "$($ReportName)_$timestamp.csv"
    
    # Export to CSV
    $Results | Export-Csv -Path $csvPath -NoTypeInformation
    
    $metadata = @{
        GeneratedBy = $env:USERNAME
        GeneratedOn = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        TotalUsers = $Results.Count
        SuccessCount = ($Results | Where-Object Status -eq "Success").Count
        FailureCount = ($Results | Where-Object Status -eq "Failed").Count
    }
    
    New-HTML -Title "Temporary Access Pass Generation Report" -FilePath $htmlPath -ShowHTML {
        New-HTMLSection -HeaderText "Generation Summary" {
            New-HTMLPanel {
                New-HTMLText -Text @"
                <h3>Report Details</h3>
                <ul>
                    <li>Generated By: $($metadata.GeneratedBy)</li>
                    <li>Generated On: $($metadata.GeneratedOn)</li>
                    <li>Total Users Processed: $($metadata.TotalUsers)</li>
                    <li>Successful Generations: $($metadata.SuccessCount)</li>
                    <li>Failed Generations: $($metadata.FailureCount)</li>
                </ul>
"@
            }
        }
        
        New-HTMLSection -HeaderText "TAP Generation Results" {
            New-HTMLTable -DataTable $Results -ScrollX -Buttons @('copyHtml5', 'excelHtml5', 'csvHtml5') -SearchBuilder {
                New-TableCondition -Name 'Status' -ComparisonType string -Operator eq -Value 'Failed' -BackgroundColor Salmon -Color Black
                New-TableCondition -Name 'Status' -ComparisonType string -Operator eq -Value 'Success' -BackgroundColor LightGreen -Color Black
                New-TableCondition -Name 'UserPrincipalName' -ComparisonType string -Operator contains -Value '' -BackgroundColor White -Color Black
                New-TableCondition -Name 'MultiUse' -ComparisonType string -Operator eq -Value $true -BackgroundColor LightBlue -Color Black
            }
        }
    }

    Write-Host "`nReports generated:" -ForegroundColor Green
    Write-Host "CSV Report: $csvPath" -ForegroundColor Green
    Write-Host "HTML Report: $htmlPath" -ForegroundColor Green
    
    return @{
        CSVPath = $csvPath
        HTMLPath = $htmlPath
    }
}